[project]
name = "paiguangguang"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "chromadb>=1.5.9",
    "fastapi>=0.139.0",
    "jwt>=1.4.0",
    "passlib>=1.7.4",
    "psycopg>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.50.0",
]
